name: Bug report
description: Template for bug reports.
labels: bug
body:
  - id: disclaimer
    type: markdown
    attributes:
      value: |
        Try to create a very concise title that's straight to the point.

        DO NOT CREATE ISSUES ABOUT SPECIFIC GAMES IN THIS REPOSITORY!
        A game specific issue would be e.g. "Game X crashes after you hit a character a certain way"
        A Xenia issue would be e.g. "Kernel export NtDoSomething does nothing"
  - id: validation
    type: checkboxes
    attributes:
      label: Validation
      options:
      - label: This issue isn't for tech support (help with Xenia).
        required: true
      - label: If this issue occurs in a specific game, I've done analysis to locate the faulty subsystem of the emulator and a potential reason in it.
        required: true
      - label: I've checked if this issue hasn't already been reported.
        required: true
  - id: problem
    type: textarea
    attributes:
      label: Describe what's going wrong
    validations:
      required: true
  - id: what-should-happen
    type: textarea
    attributes:
      label: Describe what should happen
    validations:
      required: true
  - id: callstack
    type: textarea
    attributes:
      label: If applicable, provide a callstack here, especially for crashes
  - id: logfile
    type: textarea
    attributes:
      label: If applicable, upload a logfile and link it here
